package com.example.ui.tabs

import androidx.compose.ui.graphics.Color
import com.example.data.LedgerEntryEntity
import com.example.ui.components.MetricInfo
import com.example.util.Formatters.fmtCZK

internal object CashFlowMetricInfos {
    val totalIncome = MetricInfo(
        title = "Total Monthly Inflows",
        category = "Cash Flow Engine",
        formulaOrRule = "Net Salaries + Parental Allowance + Meal Vouchers + Family Gifts",
        explanation = "Combined monthly liquid inflows available to the household. Reflects true cash generation after Czech personal income taxes (15%/23%), social security (7.1%), and health insurance (4.5%).",
        statutoryReference = "Act No. 586/1992 Coll. (ZDP)",
        practicalImplication = "Maximizing tax-exempt meal vouchers and allowances increases take-home cash without pushing you into the 23% progressive tax bracket.",
        accentColor = Color(0xFF16A34A)
    )

    val livingExpenses = MetricInfo(
        title = "Total Living Expenses",
        category = "Budget & Burn Rate",
        formulaOrRule = "Rent + Groceries + Lifestyle + Children + Discretionary",
        explanation = "Your household's monthly operational burn rate. Lowering permanent baseline living expenses has a dual effect: it immediately increases your monthly savings rate and permanently lowers your required total FIRE target capital.",
        practicalImplication = "Every 1,000 CZK/month reduction in permanent living costs lowers your required FIRE nest egg by ~342,000 CZK at a 3.5% SWR.",
        accentColor = Color(0xFF0F766E)
    )

    val childExpenses = MetricInfo(
        title = "Child Living & Education Expenses",
        category = "Family Budget",
        formulaOrRule = "Toddler (4.8k) -> Preschool (6.5k) -> School (8.5k) -> Teen (13k) -> University (10k)",
        explanation = "Child expenses age-bracketed according to Czech standard living baskets. When 'Child costs in baseline' is enabled, costs for existing children are assumed to already be embedded in baseline groceries and housing, adding 0 CZK in the base year.",
        practicalImplication = "Ensures lifecycle family cost expansion is modeled accurately without double-counting current daily spending.",
        accentColor = Color(0xFF0F766E)
    )

    val surplus = MetricInfo(
        title = "Net Monthly Cash Surplus",
        category = "Capital Generation",
        formulaOrRule = "Total Monthly Inflows - Total Living Expenses",
        explanation = "The net uncommitted capital generated by the household every month. This funds your automated monthly DCA investments (ETFs, DIP, DPS) and expands your liquid emergency reserve.",
        practicalImplication = "Maintaining a positive surplus even during single-earner or parental leave periods guarantees your long-term compound trajectory remains intact.",
        accentColor = Color(0xFF0F766E)
    )

    val vaclavSalary = MetricInfo(
        title = "Václav's Net Salary",
        category = "Earned Take-Home Pay",
        formulaOrRule = "Gross Salary - 15% Tax (less 2,570 CZK credit) - 7.1% Social - 4.5% Health",
        explanation = "Your take-home net salary after statutory employee deductions and basic taxpayer tax credit (§ 35ba(1)(a) ZDP).",
        statutoryReference = "§ 35ba odst. 1 písm. a) Act No. 586/1992 Coll.",
        accentColor = Color(0xFF0F766E)
    )

    val eleonoraSalary = MetricInfo(
        title = "Eleonora's Net Salary",
        category = "Earned Take-Home Pay",
        formulaOrRule = "Gross Salary - 15% Tax - 7.1% Social - 4.5% Health",
        explanation = "Projected net salary upon returning to employment with annual compounding career growth.",
        accentColor = Color(0xFFD97706)
    )

    val mealVouchers = MetricInfo(
        title = "Meal Voucher Cash Allowance",
        category = "Czech Tax Optimization",
        formulaOrRule = "§ 6 odst. 9 písm. b) ZDP · Non-taxable cash allowance",
        explanation = "Monetary meal allowance (stravenkový paušál) paid by employer directly into your bank account. 100% exempt from personal income tax, health insurance, and social security up to the statutory daily limit.",
        statutoryReference = "§ 6 odst. 9 písm. b) Act No. 586/1992 Coll.",
        practicalImplication = "Pure net tax-free cash equivalent to an additional ~3,000 CZK gross salary without tax drag.",
        accentColor = Color(0xFF0F766E)
    )

    val parentalBenefit = MetricInfo(
        title = "State Parental Allowance",
        category = "State Social Support",
        formulaOrRule = "350,000 CZK total entitlement · 100% tax exempt",
        explanation = "State family benefit for parents caring full-time for the youngest child. Fully tax-exempt under § 4(1)(j) ZDP. Crucially, parental allowance does NOT count into the 68,000 CZK/year spouse own income limit for the spouse tax credit (§ 35ba(1)(b)).",
        statutoryReference = "Act No. 117/1995 Coll. & § 4 odst. 1 písm. j) ZDP",
        practicalImplication = "Because parental allowance is excluded from the 68k CZK income ceiling, Václav can claim the full 24,840 CZK/yr spouse tax credit while Eleonora is on leave (for children under 3).",
        accentColor = Color(0xFFD97706)
    )

    val lecturing = MetricInfo(
        title = "Eleonora's Lecturing Income",
        category = "Academic & Side Income",
        formulaOrRule = "Independent lecturing, teaching & advisory inflows",
        explanation = "Part-time academic lecturing income. Note that lecturing income counts toward the 68,000 CZK annual spouse income ceiling for tax credit eligibility.",
        statutoryReference = "§ 35ba odst. 1 písm. b) ZDP",
        accentColor = Color(0xFFD97706)
    )

    val familyGift = MetricInfo(
        title = "Family Support Gift",
        category = "Tax Exemption",
        formulaOrRule = "§ 10 odst. 3 písm. c) ZDP · Direct Lineage Exemption",
        explanation = "Gifts and financial contributions between direct-line relatives (parents, children, grandparents) and spouses are completely exempt from Czech personal income tax without monetary ceiling.",
        statutoryReference = "§ 10 odst. 3 písm. c) Act No. 586/1992 Coll.",
        practicalImplication = "Family gifts directly supplement monthly DCA investment flows with 0% tax liability.",
        accentColor = Color(0xFF0F766E)
    )

    val vaclavGifts = MetricInfo(
        title = "Václav's Family Gifts",
        category = "Czech Tax Exemption",
        formulaOrRule = "§ 10 odst. 3 písm. c) ZDP · Tax Exempt",
        explanation = "Financial gifts from direct and indirect line relatives are 100% exempt from personal income tax without monetary limit under Czech tax law.",
        statutoryReference = "§ 10 odst. 3 písm. c) Act No. 586/1992 Coll.",
        practicalImplication = "Directly boosts monthly investment surplus with 0% tax liability.",
        accentColor = Color(0xFF16A34A)
    )

    val eleonoraGifts = MetricInfo(
        title = "Eleonora's Family Gifts",
        category = "Czech Tax Exemption",
        formulaOrRule = "§ 10 odst. 3 písm. c) ZDP · Tax Exempt & Excluded from 68k Limit",
        explanation = "Gifts from relatives are 100% tax-free and crucially do not count toward the 68,000 CZK annual spouse income ceiling (§ 35ba(1)(b) ZDP).",
        statutoryReference = "§ 10 odst. 3 písm. c) & § 35ba odst. 1 písm. b) ZDP",
        practicalImplication = "Eleonora can receive family gifts without jeopardizing the household's 24,840 CZK spouse tax credit.",
        accentColor = Color(0xFF16A34A)
    )

    val dcaInvestments = MetricInfo(
        title = "Automated Monthly DCA",
        category = "Investment Compounding",
        formulaOrRule = "Monthly ETF/Brokerage + DIP + DPS Deposits",
        explanation = "Automated dollar-cost averaging into diversified global equity index funds and tax-sheltered retirement vehicles. Eliminates market timing risk by steadily purchasing shares through market cycles.",
        practicalImplication = "Consistently investing monthly surplus accelerates net worth compounding and sequence-of-returns protection.",
        accentColor = Color(0xFF0F766E)
    )

    val dipDeduction = MetricInfo(
        title = "DIP (Dlouhodobý investiční produkt)",
        category = "Retirement Tax Shield",
        formulaOrRule = "§ 15a ZDP · Up to 48 000 CZK annual tax deduction",
        explanation = "Czech long-term investment product enabling investments into index ETFs with pre-tax income. Combined 48 000 CZK annual ceiling with DPS provides 7 200 CZK (at 15% rate) or 11 040 CZK (at 23% rate) in direct annual tax savings.",
        statutoryReference = "§ 15a Act No. 586/1992 Coll.",
        practicalImplication = "Reinvesting tax savings into your ETF portfolio creates a compound tax alpha on your retirement nest egg.",
        accentColor = Color(0xFF16A34A)
    )

    val dpsSubsidy = MetricInfo(
        title = "DPS (Doplňkové penzijní spoření)",
        category = "State Subsidy & Pension",
        formulaOrRule = "20% standard / 40% youth match + § 15(5) ZDP deduction",
        explanation = "Supplementary pension savings with direct state matching. Under 30 receives 40% state match up to 680 CZK/mo. Contributions over 1,700 CZK/mo qualify for additional personal income tax deduction.",
        statutoryReference = "Act No. 427/2011 Coll.",
        practicalImplication = "Combines guaranteed state subsidy returns with long-term compound equity growth in dynamic participation funds.",
        accentColor = Color(0xFF0F766E)
    )

    val savingsRate = MetricInfo(
        title = "Household Savings Rate",
        category = "FIRE Velocity",
        formulaOrRule = "(Total Inflows - Living Expenses) / Total Inflows",
        explanation = "The single most powerful determinant of your early retirement date. A 50%+ savings rate guarantees financial independence in ~15 years; a 65%+ rate cuts the timeline to ~10 years.",
        practicalImplication = "Every 5% boost in savings rate compounds exponentially into faster FIRE milestones.",
        accentColor = Color(0xFF0F766E)
    )

    fun ledgerIncomes(entry: LedgerEntryEntity, baselineInc: Double) = MetricInfo(
        title = "Monthly Inflows · ${entry.yearMonth}",
        category = "Actual Bank Record",
        formulaOrRule = "Václav (${fmtCZK(entry.incVaclav)}) + Eleonora (${fmtCZK(entry.incEleonora)}) + Other (${fmtCZK(entry.incUnforeseen)})",
        explanation = "Total liquid cash deposited into your household accounts during ${entry.yearMonth}. Inflows reflect net take-home pay after Czech income taxes (15%/23%), social security (7.1%), and health insurance (4.5%).",
        practicalImplication = if (entry.incVaclav + entry.incEleonora + entry.incUnforeseen >= baselineInc)
            "Inflows exceeded your standard monthly budget baseline (${fmtCZK(baselineInc)}) by ${fmtCZK((entry.incVaclav + entry.incEleonora + entry.incUnforeseen) - baselineInc)}."
        else
            "Inflows were ${fmtCZK(baselineInc - (entry.incVaclav + entry.incEleonora + entry.incUnforeseen))} below your baseline budget (${fmtCZK(baselineInc)}).",
        accentColor = Color(0xFF16A34A)
    )

    fun ledgerExpenses(entry: LedgerEntryEntity, baselineExp: Double) = MetricInfo(
        title = "Monthly Living Expenses · ${entry.yearMonth}",
        category = "Actual Bank Record",
        formulaOrRule = "Rent (${fmtCZK(entry.expRent)}) + Groceries (${fmtCZK(entry.expGroceries)}) + Other Living (${fmtCZK(entry.expOther)})",
        explanation = "Combined operational burn rate logged for ${entry.yearMonth}. Groceries and day-to-day spending are tracked separately from housing rent to highlight discretionary lifestyle inflation.",
        practicalImplication = if (entry.expRent + entry.expGroceries + entry.expOther <= baselineExp)
            "Total spending remained ${fmtCZK(baselineExp - (entry.expRent + entry.expGroceries + entry.expOther))} below your baseline plan (${fmtCZK(baselineExp)}), creating extra investment capacity."
        else
            "Spending exceeded your baseline living plan (${fmtCZK(baselineExp)}) by ${fmtCZK((entry.expRent + entry.expGroceries + entry.expOther) - baselineExp)}.",
        accentColor = Color(0xFFDC2626)
    )

    fun ledgerNetFlow(entry: LedgerEntryEntity, totalInc: Double, totalExp: Double, netFlow: Double, savingsRate: Double) = MetricInfo(
        title = "Net Cash Flow · ${entry.yearMonth}",
        category = "Actual Capital Generation",
        formulaOrRule = "Total Inflows (${fmtCZK(totalInc)}) - Living Expenses (${fmtCZK(totalExp)}) = ${fmtCZK(netFlow)}",
        explanation = "Net uncommitted liquidity produced by the household in ${entry.yearMonth}. Your savings rate for this month was ${savingsRate.toInt()}%.",
        practicalImplication = "This cash surplus funds your automated ETF DCA allocations (Portu, DIP, DPS) and expands your liquid emergency reserve.",
        accentColor = Color(0xFF0F766E)
    )

    fun ledgerBudgetVariance(diff: Double, baselineSurplus: Double, actualNet: Double) = MetricInfo(
        title = "vs Baseline Budget Performance",
        category = "Monthly Variance Analysis",
        formulaOrRule = "Actual Net (${fmtCZK(actualNet)}) - Baseline Plan Net (${fmtCZK(baselineSurplus)}) = ${if (diff >= 0) "+" else ""}${fmtCZK(diff)}",
        explanation = "Measures how much more (or less) uncommitted capital your household generated this month compared to your planned baseline financial budget.",
        practicalImplication = if (diff >= 0)
            "Positive budget outperformance. You generated ${fmtCZK(diff)} more capital than planned, accelerating your FIRE timeline."
        else
            "Negative variance of ${fmtCZK(-diff)}. Review discretionary lifestyle spending or unexpected expenses to re-align with budget.",
        accentColor = if (diff >= 0) Color(0xFF16A34A) else Color(0xFFDC2626)
    )

    fun ledgerMonthEndWealth(entry: LedgerEntryEntity) = MetricInfo(
        title = "Month-End Wealth Snapshot · ${entry.yearMonth}",
        category = "Net Worth Point-in-Time",
        formulaOrRule = "Reserve (${fmtCZK(entry.emergencyReserveAtMonthEnd)}) + Portu (${fmtCZK(entry.portfolioBalanceAtMonthEnd)}) + Pension (${fmtCZK(entry.pensionBalanceAtMonthEnd)})",
        explanation = "Your point-in-time closing balance of liquid safety reserves and tracked investment portfolios as of the end of ${entry.yearMonth}.",
        practicalImplication = "Tracking your month-end cash reserve ensures your emergency runway (6+ months) remains protected as market values fluctuate.",
        accentColor = Color(0xFFD97706)
    )

    fun ledgerBankImport(entry: LedgerEntryEntity) = MetricInfo(
        title = "Bank Statement Source & Provenance",
        category = "Automated Import Record",
        formulaOrRule = entry.notes.ifBlank { "Direct Bank Statement Import" },
        explanation = "This month's figures were automatically populated from your bank statement. Inflows, grocery purchases, and retirement contributions were categorized, and internal transfers between Moneta, ČSOB, and mBank were netted out to prevent double counting.",
        practicalImplication = "The closing accounting balance was automatically stored as your liquid emergency reserve for this month.",
        accentColor = Color(0xFF0F766E)
    )
}
