package com.example.ui.tabs

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.domain.FullCalculationState
import com.example.ui.components.CardHeaderPill
import com.example.ui.components.KpiCard
import com.example.ui.components.NetWorthChart
import com.example.ui.theme.BadRed
import com.example.ui.theme.BrandBlue
import com.example.ui.theme.BrandGold
import com.example.ui.theme.BrandTeal
import com.example.ui.theme.GoodGreen
import com.example.util.Formatters.fmtCZK
import com.example.util.Formatters.fmtCompact
import com.example.util.Formatters.fmtPct

import com.example.ui.components.EmergencyReserveWidget
import com.example.ui.components.MetricInfo
import com.example.ui.components.MetricInfoDialog
import com.example.ui.components.infoTapHold
import com.example.ui.components.rememberMetricInfoState
import com.example.data.LedgerEntryEntity
import com.example.data.SettingsEntity

@Composable
fun OverviewTab(
    state: FullCalculationState,
    ledgerEntries: List<LedgerEntryEntity> = emptyList(),
    actionStates: Map<String, Boolean> = emptyMap(),
    onToggleAction: ((year: Int, actionId: String, currentIsDone: Boolean) -> Unit)? = null,
    onNavigateToIncome: (() -> Unit)? = null,
    onNavigateToProjections: (() -> Unit)? = null,
    onNavigateToPlan: (() -> Unit)? = null,
    onUpdateSettings: ((SettingsEntity) -> Unit)? = null,
    modifier: Modifier = Modifier
) {
    val scrollState = rememberScrollState()
    val infoState = rememberMetricInfoState()

    val incomeInfo = MetricInfo(
        title = "Household Net Inflows",
        category = "Cash Flow & Inflows",
        formulaOrRule = "Salaries + Benefits + Vouchers + Gifts + Inflows + Lump Sums",
        explanation = "Measures true monthly cash generation after all personal Czech taxes (15%/23%), social security (7.1%), and health insurance (4.5%). Includes meal vouchers, tax-exempt family gifts (§ 10 ZDP), parental allowance, and lecturing.",
        statutoryReference = "Act No. 586/1992 Coll. (Income Tax Act)",
        practicalImplication = "Accurately represents the total disposable cash generated by the household each month for living expenses and DCA investing.",
        accentColor = BrandTeal
    )

    val pensionAgeDesc = if (state.settings.vStatePensionAge == state.settings.eStatePensionAge) {
        "age ${state.settings.vStatePensionAge}"
    } else {
        "ages ${state.settings.vStatePensionAge}/${state.settings.eStatePensionAge}"
    }
    val fireTargetInfo = MetricInfo(
        title = "Base FIRE Target Capital",
        category = "Retirement Actuarial Target",
        formulaOrRule = "Target = (Annual Living Burn - State Pension) / SWR + Bridge Deficit",
        explanation = "Calculated in today's constant purchasing power (real CZK). It accounts for the multi-decade bridge period where private investment assets must sustain 100% of household expenditures before the Czech state pension kicks in at $pensionAgeDesc.",
        statutoryReference = "Act No. 155/1995 Coll. (Pension Insurance Act)",
        practicalImplication = "Every 1,000 CZK/month reduction in permanent baseline living expenses reduces required FIRE capital by ~342,000 CZK at a 3.5% SWR.",
        accentColor = BrandGold
    )

    val firePoint = if (state.settings.isSingleHousehold) state.fireSinglePoint else state.fireDualPoint
    val fireAgeInfo = MetricInfo(
        title = "Projected FIRE Horizon",
        category = "Trajectory Milestone",
        formulaOrRule = "Compound DCA + Organic Growth >= Dynamic FIRE Target",
        explanation = "Determined dynamically by modeling when aggregate liquid brokerage investments, DIP, and accessible retirement assets surpass the required cost-of-living capital barrier under inflation and real return assumptions.",
        practicalImplication = "Front-loading savings rate early compounds exponentially due to sequence-of-returns acceleration in initial accumulation years.",
        accentColor = BrandBlue
    )

    val netWorthInfo = MetricInfo(
        title = "Consolidated Net Worth",
        category = "Balance Sheet",
        formulaOrRule = "Liquid Brokerage + DIP + DPS + Emergency Cash",
        explanation = "Represents consolidated financial capital. Excludes illiquid primary residential real estate equity to ensure strict FIRE withdrawal modeling against income-generating assets.",
        practicalImplication = "Tracking liquid investment equity versus emergency cash preserves an optimal allocation between cash drag and compounding growth.",
        accentColor = GoodGreen
    )

    Column(
        modifier = modifier
            .fillMaxSize()
            .verticalScroll(scrollState)
            .padding(16.dp)
            .testTag("overview_tab")
    ) {
        // 4 Interactive KPI Cards (Symmetric 2x2 Grid, Tap / Hold for deep insight)
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            KpiCard(
                title = "Household Net / Mo",
                value = fmtCZK(state.currentIncome.totalMonthly),
                hint = "Combined family income",
                accentColor = BrandTeal,
                modifier = Modifier.weight(1f),
                testTagStr = "kpi_family_net",
                info = incomeInfo,
                onShowInfo = { infoState.show(it) },
                onClick = onNavigateToIncome
            )

            KpiCard(
                title = "Base FIRE Target",
                value = fmtCompact(state.fireBaseTargetToday),
                hint = "Today's purchasing power",
                accentColor = BrandGold,
                modifier = Modifier.weight(1f),
                testTagStr = "kpi_fire_target",
                info = fireTargetInfo,
                onShowInfo = { infoState.show(it) },
                onClick = onNavigateToProjections
            )
        }

        Spacer(modifier = Modifier.height(12.dp))

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            KpiCard(
                title = "Projected FIRE Age",
                value = firePoint?.let { "Age ${it.age}" } ?: "Age ${state.settings.primaryAge + 35}+",
                hint = firePoint?.let { "Projected year ${it.year}" } ?: "Beyond 35y horizon",
                accentColor = BrandBlue,
                modifier = Modifier.weight(1f),
                testTagStr = "kpi_fire_age",
                info = fireAgeInfo,
                onShowInfo = { infoState.show(it) },
                onClick = onNavigateToProjections
            )

            KpiCard(
                title = "Net Worth Total",
                value = fmtCompact(state.netWorthTotal),
                hint = "Liquid + reserve + pension",
                accentColor = GoodGreen,
                modifier = Modifier.weight(1f),
                testTagStr = "kpi_net_worth",
                info = netWorthInfo,
                onShowInfo = { infoState.show(it) },
                onClick = onNavigateToProjections
            )
        }

        Spacer(modifier = Modifier.height(14.dp))

        // Emergency Reserve & Runway Goal Tracker Widget
        EmergencyReserveWidget(
            state = state,
            onShowInfo = { infoState.show(it) },
            onUpdateSettings = onUpdateSettings
        )

        Spacer(modifier = Modifier.height(16.dp))

        // Net Worth Chart
        NetWorthChart(
            data = if (state.settings.isSingleHousehold) state.singleTrajectory else state.dualTrajectory,
            cpiInflationPct = state.settings.cpiInflationPct,
            ledgerEntries = ledgerEntries
        )

        Spacer(modifier = Modifier.height(16.dp))

        // Quick Highlights
        val surplusVal = state.currentIncome.totalMonthly - state.totalLivingCostMonthly
        val surplusInfo = MetricInfo(
            title = "Monthly Capital Surplus",
            category = "Cash Flow & DCA Engine",
            formulaOrRule = "Surplus = Total Net Monthly Inflows - All Fixed/Variable Living Expenses",
            explanation = "Represents your monthly discretionary investment firepower. In pure FIRE math, your savings rate (Surplus / Inflows) is the single most dominant lever governing years-to-financial-independence, outweighing investment returns during early accumulation.",
            practicalImplication = "Directing surplus automatically on pay-day into index ETFs and DIP eliminates lifestyle creep and enforces paying yourself first.",
            accentColor = BrandTeal
        )

        val dipSavingInfo = MetricInfo(
            title = "DIP & DPS Statutory Tax Shield",
            category = "Czech Tax Optimization",
            formulaOrRule = "Tax Refund = min(DIP + DPS Deposits - Subsidy Threshold, 48k CZK) × Tax Rate (15% / 23%)",
            explanation = "Under § 15a of the Czech Income Tax Act (ZDP), taxpayers can deduct up to 48,000 CZK combined annually from their personal taxable base across qualifying Long-Term Investment Products (DIP) and Supplementary Pension Savings (DPS).",
            statutoryReference = "§ 15 odst. 5 & § 15a Act No. 586/1992 Coll. (ZDP)",
            practicalImplication = "Contributing 4,000 CZK/month into DIP unlocks the full 48k ceiling, providing an immediate risk-free 15% (7,200 CZK) or 23% (11,040 CZK) annual tax refund.",
            accentColor = GoodGreen
        )

        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(16.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)),
            border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.35f))
        ) {
            Column(modifier = Modifier.padding(16.dp)) {
                CardHeaderPill(
                    title = "Strategic Highlights",
                    subtitle = "Monthly dynamics & tax efficiency (Tap for deep insight)",
                    badgeText = "KEY STATS",
                    accentColor = BrandTeal
                )
                Spacer(modifier = Modifier.height(14.dp))
                SummaryRow(
                    label = "Monthly surplus",
                    value = fmtCZK(surplusVal),
                    valueColor = if (surplusVal < 0) BadRed else GoodGreen,
                    info = surplusInfo,
                    onShowInfo = { infoState.show(it) }
                )
                Spacer(modifier = Modifier.height(8.dp))
                SummaryRow(
                    label = "Monthly savings rate",
                    value = fmtPct(state.savingsRatePct, 1),
                    info = MetricInfo(
                        title = "Monthly Investment Rate",
                        category = "Wealth Accumulation Velocity",
                        formulaOrRule = "Investment Rate = Automated Monthly Investments (DCA) / Total Net Inflows",
                        explanation = "Measures the percentage of total household net income channeled directly into automated wealth-building vehicles (Brokerage/ETF, DIP, and DPS).",
                        practicalImplication = "Elevating investment rate accelerates FIRE milestones by boosting compounding capital while curbing lifestyle creep.",
                        accentColor = BrandTeal
                    ),
                    onShowInfo = { infoState.show(it) }
                )
                val coastMilestone = state.fireMilestones.coastFire
                SummaryRow(
                    label = if (coastMilestone.isAchieved) "Coast FIRE achieved" else "Coast FIRE progress",
                    value = if (coastMilestone.isAchieved) {
                        "Age ${coastMilestone.estimatedAge ?: "—"}"
                    } else {
                        fmtPct(coastMilestone.progressPct, 0)
                    },
                    valueColor = if (coastMilestone.isAchieved) GoodGreen else BrandGold,
                    info = MetricInfo(
                        title = "Coast FIRE",
                        category = "Financial Independence Milestones",
                        formulaOrRule = "Coast FIRE Target = FIRE Target / (1 + Real Return)^(Years to Age 65)",
                        explanation = "Coast FIRE is the portfolio size at which compound growth alone — with zero further contributions — will reach your full FIRE target by traditional retirement age. Once reached, you could theoretically stop saving entirely and still retire on time.",
                        practicalImplication = if (coastMilestone.isAchieved) {
                            "You have crossed the Coast FIRE threshold. Every additional contribution now accelerates your FIRE date beyond the baseline."
                        } else {
                            "You are ${fmtPct(coastMilestone.progressPct, 0)} of the way to Coast FIRE (target: ${fmtCompact(coastMilestone.targetAmountToday)}). Keep contributing to reach this milestone."
                        },
                        accentColor = if (coastMilestone.isAchieved) GoodGreen else BrandGold
                    ),
                    onShowInfo = { infoState.show(it) }
                )
                val baristaMilestone = state.fireMilestones.baristaFire
                if (baristaMilestone != null) {
                    SummaryRow(
                        label = if (baristaMilestone.isAchieved) "Barista FIRE achieved" else "Barista FIRE progress",
                        value = if (baristaMilestone.isAchieved) {
                            "Age ${baristaMilestone.estimatedAge ?: "—"}"
                        } else {
                            fmtPct(baristaMilestone.progressPct, 0)
                        },
                        valueColor = if (baristaMilestone.isAchieved) GoodGreen else BrandGold,
                        info = MetricInfo(
                            title = "Barista FIRE",
                            category = "Financial Independence Milestones",
                            formulaOrRule = "Barista FIRE Target = 50% of Full FIRE Target",
                            explanation = "Barista FIRE means your portfolio covers 50% of your household expenses indefinitely. You only need part-time, freelance, or low-stress work to cover the other half.",
                            practicalImplication = if (baristaMilestone.isAchieved) {
                                "You have reached Barista FIRE. Your invested capital covers 50% of baseline living expenses."
                            } else {
                                "You are ${fmtPct(baristaMilestone.progressPct, 0)} of the way to Barista FIRE (target: ${fmtCompact(baristaMilestone.targetAmountToday)})."
                            },
                            accentColor = if (baristaMilestone.isAchieved) GoodGreen else BrandGold
                        ),
                        onShowInfo = { infoState.show(it) }
                    )
                }
                if (state.dip.taxSavedYear > 0) {
                    Spacer(modifier = Modifier.height(8.dp))
                    SummaryRow(
                        label = "DIP / DPS tax savings",
                        value = "${fmtCZK(state.dip.taxSavedYear)}/yr",
                        valueColor = GoodGreen,
                        info = dipSavingInfo,
                        onShowInfo = { infoState.show(it) }
                    )
                }
            }
        }


        Spacer(modifier = Modifier.height(96.dp))
    }

    // Modal Metric Info Dialog
    MetricInfoDialog(
        info = infoState.currentInfo,
        onDismiss = { infoState.dismiss() }
    )
}

@Composable
private fun SummaryRow(
    label: String,
    value: String,
    info: MetricInfo? = null,
    onShowInfo: ((MetricInfo) -> Unit)? = null,
    valueColor: androidx.compose.ui.graphics.Color = BrandTeal
) {
    val clickModifier = if (info != null && onShowInfo != null) {
        Modifier
            .clip(RoundedCornerShape(8.dp))
            .infoTapHold(info, onShowInfo)
    } else Modifier

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .then(clickModifier)
            .padding(vertical = 2.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.weight(1f).padding(end = 8.dp)
        ) {
            Text(
                text = "• $label:",
                style = MaterialTheme.typography.bodyMedium
            )
            if (info != null) {
                Spacer(modifier = Modifier.width(4.dp))
                Icon(
                    imageVector = Icons.Default.CheckCircle,
                    contentDescription = "Info available",
                    tint = BrandTeal.copy(alpha = 0.5f),
                    modifier = Modifier.size(13.dp)
                )
            }
        }
        Text(
            text = value,
            style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Bold),
            color = valueColor,
            textAlign = androidx.compose.ui.text.style.TextAlign.End,
            modifier = Modifier.weight(1f)
        )
    }
}
