package com.example.util

import java.io.ByteArrayOutputStream
import java.nio.charset.Charset
import java.util.Locale
import java.util.zip.Inflater

/**
 * Lightweight, zero-dependency PDF text extractor in pure Kotlin.
 *
 * Extracts text streams from PDF documents (PDF 1.0 - 1.7) generated by standard banking
 * systems (Moneta, CSOB, mBank). Handles FlateDecode stream decompression, ToUnicode CMaps,
 * PDF literal string escapes, hex strings, TJ positioning arrays, and Czech diacritics
 * (Windows-1250, UTF-8, and UTF-16BE).
 */
object PdfTextExtractor {

    private val cp1250Charset: Charset by lazy {
        try {
            Charset.forName("windows-1250")
        } catch (_: Exception) {
            Charsets.ISO_8859_1
        }
    }

    /** Upper bound for a single inflated PDF stream, to defend against decompression bombs. */
    private const val MAX_INFLATED_BYTES = 40 * 1024 * 1024

    private data class PdfStream(
        val dictionary: String,
        val data: ByteArray
    )

    fun isPdf(bytes: ByteArray): Boolean {
        if (bytes.size < 4) return false
        val prefix = bytes.take(1024).toByteArray()
        val ascii = String(prefix, Charsets.US_ASCII)
        return ascii.contains("%PDF-")
    }

    fun extractText(pdfBytes: ByteArray): String {
        if (!isPdf(pdfBytes)) return ""

        val streams = extractRawStreams(pdfBytes)
        val cMap = mutableMapOf<Int, String>()

        // 1. First pass: Find and parse /ToUnicode CMaps across all streams
        for (stream in streams) {
            val decompressed = decompressStream(stream) ?: continue
            val textSample = String(decompressed.take(4096).toByteArray(), Charsets.US_ASCII)
            if (stream.dictionary.contains("/ToUnicode") || textSample.contains("beginbfchar") || textSample.contains("beginbfrange")) {
                parseCMap(decompressed, cMap)
            }
        }

        // 2. Second pass: Extract text from content streams
        val extractedLines = mutableListOf<String>()
        for (stream in streams) {
            // Skip non-content streams (images, metadata, font programs, ToUnicode CMaps)
            val dict = stream.dictionary
            if (dict.contains("/Subtype /Image") || dict.contains("/Subtype/Image") ||
                dict.contains("/Type /XRef") || dict.contains("/Type/XRef") ||
                dict.contains("/Type /Font") || dict.contains("/Type/Font") ||
                dict.contains("/Type /FontDescriptor") || dict.contains("/Type/FontDescriptor") ||
                dict.contains("/Length1") || dict.contains("/Length2") || dict.contains("/Length3") ||
                dict.contains("/FontFile") || dict.contains("/ToUnicode")
            ) {
                continue
            }

            val decompressed = decompressStream(stream) ?: continue
            val linesFromStream = extractTextFromDecompressedStream(decompressed, cMap)
            if (linesFromStream.isNotEmpty()) {
                extractedLines.addAll(linesFromStream)
            }
        }

        // 3. Fallback: if no content stream produced text, scan uncompressed ASCII segments
        if (extractedLines.isEmpty()) {
            val rawText = String(pdfBytes, cp1250Charset)
            val fallbackLines = extractFallbackText(rawText)
            if (fallbackLines.isNotEmpty()) {
                return fallbackLines.joinToString("\n")
            }
        }

        return extractedLines.joinToString("\n")
    }

    private fun extractRawStreams(bytes: ByteArray): List<PdfStream> {
        val result = mutableListOf<PdfStream>()
        val len = bytes.size
        var i = 0

        val streamKeyword = "stream".toByteArray(Charsets.US_ASCII)
        val endstreamKeyword = "endstream".toByteArray(Charsets.US_ASCII)

        while (i < len - 7) {
            if (matchBytes(bytes, i, streamKeyword)) {
                // Verify boundary before "stream" (must be whitespace or newline)
                val before = if (i > 0) bytes[i - 1].toInt().toChar() else ' '
                if (before.isWhitespace()) {
                    var dataStart = i + streamKeyword.size
                    // Skip \r\n or \n
                    if (dataStart < len && bytes[dataStart] == '\r'.code.toByte()) dataStart++
                    if (dataStart < len && bytes[dataStart] == '\n'.code.toByte()) dataStart++

                    // Find "endstream"
                    var endIdx = -1
                    var j = dataStart
                    while (j <= len - endstreamKeyword.size) {
                        if (matchBytes(bytes, j, endstreamKeyword)) {
                            endIdx = j
                            break
                        }
                        j++
                    }

                    if (endIdx != -1 && endIdx >= dataStart) {
                        // Trim trailing \r or \n before endstream
                        var dataEnd = endIdx
                        if (dataEnd > dataStart && bytes[dataEnd - 1] == '\n'.code.toByte()) dataEnd--
                        if (dataEnd > dataStart && bytes[dataEnd - 1] == '\r'.code.toByte()) dataEnd--

                        val streamData = bytes.copyOfRange(dataStart, dataEnd)

                        // Scan backwards from 'i' to find dictionary << ... >>
                        val dictString = extractPrecedingDictionary(bytes, i)
                        result.add(PdfStream(dictString, streamData))

                        i = endIdx + endstreamKeyword.size
                        continue
                    }
                }
            }
            i++
        }
        return result
    }

    private fun extractPrecedingDictionary(bytes: ByteArray, streamStart: Int): String {
        val lookbackMax = 4096
        val start = (streamStart - lookbackMax).coerceAtLeast(0)
        val chunk = bytes.copyOfRange(start, streamStart)
        val str = String(chunk, Charsets.US_ASCII)
        val lastClose = str.lastIndexOf(">>")
        if (lastClose == -1) return str

        // Scan backwards from lastClose to find matching outer <<
        var depth = 0
        var i = lastClose + 1
        var openIdx = -1
        while (i >= 1) {
            if (str[i] == '>' && str[i - 1] == '>') {
                depth++
                i -= 2
                continue
            }
            if (str[i] == '<' && str[i - 1] == '<') {
                depth--
                if (depth == 0) {
                    openIdx = i - 1
                    break
                }
                i -= 2
                continue
            }
            i--
        }

        return if (openIdx != -1) {
            str.substring(openIdx, lastClose + 2)
        } else {
            val firstOpen = str.lastIndexOf("<<", lastClose)
            if (firstOpen != -1) str.substring(firstOpen, lastClose + 2) else str
        }
    }

    private fun matchBytes(src: ByteArray, start: Int, target: ByteArray): Boolean {
        if (start + target.size > src.size) return false
        for (k in target.indices) {
            if (src[start + k] != target[k]) return false
        }
        return true
    }

    private fun decompressStream(stream: PdfStream): ByteArray? {
        val dict = stream.dictionary
        val isFlate = dict.contains("/FlateDecode") || dict.contains("/Flate") ||
                (stream.data.size >= 2 && stream.data[0] == 0x78.toByte())

        if (!isFlate) {
            return stream.data
        }

        fun inflate(nowrap: Boolean): ByteArray? {
            return try {
                val inflater = Inflater(nowrap)
                inflater.setInput(stream.data)
                val bos = ByteArrayOutputStream()
                val buffer = ByteArray(4096)
                while (!inflater.finished()) {
                    val count = inflater.inflate(buffer)
                    if (count == 0) {
                        if (inflater.needsInput() || inflater.needsDictionary()) break
                        continue
                    }
                    if (bos.size() + count > MAX_INFLATED_BYTES) {
                        // Decompression bomb guard: abandon and let the caller use raw data.
                        inflater.end()
                        return null
                    }
                    bos.write(buffer, 0, count)
                }
                inflater.end()
                bos.toByteArray().takeIf { it.isNotEmpty() }
            } catch (_: Exception) {
                null
            }
        }

        // 1. Standard RFC 1950 zlib, then 2. raw RFC 1951 deflate.
        inflate(false)?.let { return it }
        inflate(true)?.let { return it }
        return stream.data
    }

    private fun parseCMap(bytes: ByteArray, cMap: MutableMap<Int, String>) {
        val content = String(bytes, Charsets.US_ASCII)
        val lines = content.lines()

        var inBfChar = false
        var inBfRange = false
        var inRangeArray = false
        var rangeArrayCode = 0

        for (line in lines) {
            val trimmed = line.trim()
            if (trimmed.contains("beginbfchar")) {
                inBfChar = true
                continue
            }
            if (trimmed.contains("endbfchar")) {
                inBfChar = false
                continue
            }
            if (trimmed.contains("beginbfrange")) {
                inBfRange = true
                continue
            }
            if (trimmed.contains("endbfrange")) {
                inBfRange = false
                inRangeArray = false
                continue
            }

            if (inBfChar) {
                // Format: <srcHex> <dstHex>
                val hexes = Regex("""<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>""").findAll(trimmed)
                for (match in hexes) {
                    val src = match.groupValues[1].toIntOrNull(16) ?: continue
                    val dstHex = match.groupValues[2]
                    val dstStr = hexToUnicodeString(dstHex)
                    cMap[src] = dstStr
                }
            } else if (inBfRange) {
                val arrStartMatch = Regex("""<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*\[""").find(trimmed)
                if (arrStartMatch != null) {
                    rangeArrayCode = arrStartMatch.groupValues[1].toIntOrNull(16) ?: 0
                    inRangeArray = true
                    val afterBracket = trimmed.substring(trimmed.indexOf('[') + 1)
                    val hexes = Regex("""<([0-9A-Fa-f]+)>""").findAll(afterBracket)
                    for (h in hexes) {
                        cMap[rangeArrayCode++] = hexToUnicodeString(h.groupValues[1])
                    }
                    if (afterBracket.contains(']')) {
                        inRangeArray = false
                    }
                } else if (inRangeArray) {
                    val beforeBracket = if (trimmed.contains(']')) {
                        inRangeArray = false
                        trimmed.substring(0, trimmed.indexOf(']'))
                    } else trimmed
                    val hexes = Regex("""<([0-9A-Fa-f]+)>""").findAll(beforeBracket)
                    for (h in hexes) {
                        cMap[rangeArrayCode++] = hexToUnicodeString(h.groupValues[1])
                    }
                } else {
                    // Format: <startHex> <endHex> <dstStartHex>
                    val rangeMatch = Regex("""<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>""").find(trimmed)
                    if (rangeMatch != null) {
                        val start = rangeMatch.groupValues[1].toIntOrNull(16) ?: continue
                        val end = rangeMatch.groupValues[2].toIntOrNull(16) ?: continue
                        var dst = rangeMatch.groupValues[3].toIntOrNull(16) ?: continue
                        for (code in start..end) {
                            cMap[code] = String(Character.toChars(dst))
                            dst++
                        }
                    }
                }
            }
        }
    }

    private fun hexToUnicodeString(hex: String): String {
        val sb = StringBuilder()
        var i = 0
        while (i + 4 <= hex.length) {
            val code = hex.substring(i, i + 4).toIntOrNull(16)
            if (code != null) {
                sb.append(code.toChar())
            }
            i += 4
        }
        if (sb.isEmpty() && hex.length == 2) {
            val code = hex.toIntOrNull(16)
            if (code != null) sb.append(code.toChar())
        }
        return sb.toString()
    }

    private data class TextFragment(
        val x: Double,
        val y: Double,
        val text: String
    )

    private fun extractTextFromDecompressedStream(
        bytes: ByteArray,
        cMap: Map<Int, String>
    ): List<String> {
        val result = mutableListOf<String>()
        val len = bytes.size
        val fragments = mutableListOf<TextFragment>()

        var curX = 0.0
        var curY = 0.0
        var lineStartX = 0.0
        var lineStartY = 0.0
        var inText = false
        val numBuffer = mutableListOf<Double>()
        val pendingToken = StringBuilder()

        var i = 0
        while (i < len) {
            val b = bytes[i].toInt().toChar()

            // Check for BT / ET operators
            if (b == 'B' && i + 1 < len && bytes[i + 1].toInt().toChar() == 'T' && isTokenBoundary(bytes, i - 1, i + 2)) {
                inText = true
                curX = 0.0
                curY = 0.0
                lineStartX = 0.0
                lineStartY = 0.0
                numBuffer.clear()
                pendingToken.setLength(0)
                i += 2
                continue
            }
            if (b == 'E' && i + 1 < len && bytes[i + 1].toInt().toChar() == 'T' && isTokenBoundary(bytes, i - 1, i + 2)) {
                inText = false
                numBuffer.clear()
                pendingToken.setLength(0)
                i += 2
                continue
            }

            if (!inText) {
                i++
                continue
            }

            // Inside BT ... ET:
            when {
                // String literal: (...)
                b == '(' -> {
                    if (pendingToken.isNotEmpty()) {
                        val num = pendingToken.toString().toDoubleOrNull()
                        if (num != null) numBuffer.add(num)
                        pendingToken.setLength(0)
                    }

                    val strEnd = findStringLiteralEnd(bytes, i)
                    val rawStrBytes = bytes.copyOfRange(i + 1, strEnd)
                    val decoded = decodePdfLiteralBytes(rawStrBytes, cMap)

                    var opIdx = strEnd + 1
                    while (opIdx < len && bytes[opIdx].toInt().toChar().isWhitespace()) opIdx++
                    if (opIdx < len && bytes[opIdx].toInt().toChar() == '\'') {
                        lineStartY -= 12.0
                        curX = lineStartX
                        curY = lineStartY
                        if (decoded.isNotBlank()) fragments.add(TextFragment(curX, curY, decoded))
                        i = opIdx + 1
                    } else if (opIdx + 1 < len && bytes[opIdx].toInt().toChar() == 'T' && bytes[opIdx + 1].toInt().toChar() == 'j') {
                        if (decoded.isNotBlank()) fragments.add(TextFragment(curX, curY, decoded))
                        i = opIdx + 2
                    } else {
                        if (decoded.isNotBlank()) fragments.add(TextFragment(curX, curY, decoded))
                        i = strEnd + 1
                    }
                    numBuffer.clear()
                }

                // Hex string: <...>
                b == '<' && i + 1 < len && bytes[i + 1].toInt().toChar() != '<' -> {
                    if (pendingToken.isNotEmpty()) {
                        val num = pendingToken.toString().toDoubleOrNull()
                        if (num != null) numBuffer.add(num)
                        pendingToken.setLength(0)
                    }

                    val hexEnd = findHexEnd(bytes, i)
                    val hexText = String(bytes.copyOfRange(i + 1, hexEnd), Charsets.US_ASCII).replace(" ", "")
                    val decoded = decodeHexText(hexText, cMap)

                    var opIdx = hexEnd + 1
                    while (opIdx < len && bytes[opIdx].toInt().toChar().isWhitespace()) opIdx++
                    if (opIdx + 1 < len && bytes[opIdx].toInt().toChar() == 'T' && bytes[opIdx + 1].toInt().toChar() == 'j') {
                        if (decoded.isNotBlank()) fragments.add(TextFragment(curX, curY, decoded))
                        i = opIdx + 2
                    } else {
                        if (decoded.isNotBlank()) fragments.add(TextFragment(curX, curY, decoded))
                        i = hexEnd + 1
                    }
                    numBuffer.clear()
                }

                // Array: [...] TJ
                b == '[' -> {
                    if (pendingToken.isNotEmpty()) {
                        val num = pendingToken.toString().toDoubleOrNull()
                        if (num != null) numBuffer.add(num)
                        pendingToken.setLength(0)
                    }

                    val arrEnd = findArrayEnd(bytes, i)
                    val arrBytes = bytes.copyOfRange(i + 1, arrEnd)
                    val parsedArrayText = parseTjArray(arrBytes, cMap)

                    var opIdx = arrEnd + 1
                    while (opIdx < len && bytes[opIdx].toInt().toChar().isWhitespace()) opIdx++
                    if (opIdx + 1 < len && bytes[opIdx].toInt().toChar() == 'T' && bytes[opIdx + 1].toInt().toChar() == 'J') {
                        if (parsedArrayText.isNotBlank()) fragments.add(TextFragment(curX, curY, parsedArrayText))
                        i = opIdx + 2
                    } else {
                        if (parsedArrayText.isNotBlank()) fragments.add(TextFragment(curX, curY, parsedArrayText))
                        i = arrEnd + 1
                    }
                    numBuffer.clear()
                }

                b.isWhitespace() -> {
                    if (pendingToken.isNotEmpty()) {
                        val tok = pendingToken.toString()
                        pendingToken.setLength(0)
                        val num = tok.toDoubleOrNull()
                        if (num != null) {
                            numBuffer.add(num)
                            if (numBuffer.size > 8) numBuffer.removeAt(0)
                        } else {
                            when (tok) {
                                "Td", "TD" -> {
                                    if (numBuffer.size >= 2) {
                                        val tx = numBuffer[numBuffer.size - 2]
                                        val ty = numBuffer[numBuffer.size - 1]
                                        lineStartX += tx
                                        lineStartY += ty
                                        curX = lineStartX
                                        curY = lineStartY
                                    }
                                    numBuffer.clear()
                                }
                                "Tm" -> {
                                    if (numBuffer.size >= 6) {
                                        val tx = numBuffer[numBuffer.size - 2]
                                        val ty = numBuffer[numBuffer.size - 1]
                                        lineStartX = tx
                                        lineStartY = ty
                                        curX = tx
                                        curY = ty
                                    }
                                    numBuffer.clear()
                                }
                                "T*" -> {
                                    lineStartY -= 12.0
                                    curX = lineStartX
                                    curY = lineStartY
                                    numBuffer.clear()
                                }
                                else -> {
                                    numBuffer.clear()
                                }
                            }
                        }
                    }
                    i++
                }

                else -> {
                    pendingToken.append(b)
                    i++
                }
            }
        }

        if (fragments.isNotEmpty()) {
            val yGroups = mutableListOf<MutableList<TextFragment>>()
            for (frag in fragments) {
                val existingGroup = yGroups.firstOrNull { group ->
                    kotlin.math.abs(group.first().y - frag.y) <= 2.0
                }
                if (existingGroup != null) {
                    existingGroup.add(frag)
                } else {
                    yGroups.add(mutableListOf(frag))
                }
            }

            yGroups.sortByDescending { it.first().y }

            for (group in yGroups) {
                group.sortBy { it.x }
                val line = group.joinToString(" ") { it.text }.trim()
                if (line.isNotBlank()) {
                    result.add(line)
                }
            }
        }

        return result
    }

    private fun isTokenBoundary(bytes: ByteArray, before: Int, after: Int): Boolean {
        val bValid = before < 0 || bytes[before].toInt().toChar().isWhitespace() || bytes[before].toInt().toChar() == '/'
        val aValid = after >= bytes.size || bytes[after].toInt().toChar().isWhitespace() || bytes[after].toInt().toChar() == '/'
        return bValid && aValid
    }

    private fun findStringLiteralEnd(bytes: ByteArray, start: Int): Int {
        var depth = 1
        var i = start + 1
        val len = bytes.size
        while (i < len) {
            val b = bytes[i]
            if (b == '\\'.code.toByte()) {
                i += 2 // skip escape
                continue
            }
            if (b == '('.code.toByte()) depth++
            if (b == ')'.code.toByte()) {
                depth--
                if (depth == 0) return i
            }
            i++
        }
        return len - 1
    }

    private fun findHexEnd(bytes: ByteArray, start: Int): Int {
        var i = start + 1
        while (i < bytes.size) {
            if (bytes[i] == '>'.code.toByte()) return i
            i++
        }
        return bytes.size - 1
    }

    private fun findArrayEnd(bytes: ByteArray, start: Int): Int {
        var i = start + 1
        var inParen = false
        var inHex = false
        while (i < bytes.size) {
            val b = bytes[i]
            if (b == '\\'.code.toByte() && inParen) {
                i += 2
                continue
            }
            if (b == '('.code.toByte() && !inHex) inParen = true
            if (b == ')'.code.toByte() && inParen) inParen = false
            if (b == '<'.code.toByte() && !inParen) inHex = true
            if (b == '>'.code.toByte() && inHex) inHex = false
            if (b == ']'.code.toByte() && !inParen && !inHex) return i
            i++
        }
        return bytes.size - 1
    }

    private fun parseTjArray(arrBytes: ByteArray, cMap: Map<Int, String>): String {
        val sb = StringBuilder()
        var i = 0
        val len = arrBytes.size
        while (i < len) {
            val c = arrBytes[i].toInt().toChar()
            if (c == '(') {
                val strEnd = findStringLiteralEnd(arrBytes, i)
                val raw = arrBytes.copyOfRange(i + 1, strEnd)
                sb.append(decodePdfLiteralBytes(raw, cMap))
                i = strEnd + 1
            } else if (c == '<') {
                val hexEnd = findHexEnd(arrBytes, i)
                val hex = String(arrBytes.copyOfRange(i + 1, hexEnd), Charsets.US_ASCII).replace(" ", "")
                sb.append(decodeHexText(hex, cMap))
                i = hexEnd + 1
            } else if (c.isDigit() || c == '-') {
                val numStart = i
                while (i < len && (arrBytes[i].toInt().toChar().isDigit() || arrBytes[i].toInt().toChar() == '-' || arrBytes[i].toInt().toChar() == '.')) {
                    i++
                }
                val numStr = String(arrBytes.copyOfRange(numStart, i), Charsets.US_ASCII)
                val spacing = numStr.toDoubleOrNull()
                // In PDF TJ arrays, negative numbers represent moving to the right.
                // Significant negative values (< -110) indicate a word space.
                if (spacing != null && spacing < -110.0) {
                    if (sb.isNotEmpty() && !sb.endsWith(' ')) {
                        sb.append(' ')
                    }
                }
            } else {
                i++
            }
        }
        return sb.toString()
    }

    private fun decodePdfLiteralBytes(rawBytes: ByteArray, cMap: Map<Int, String>): String {
        // Unescape PDF escapes
        val unescaped = ByteArrayOutputStream()
        var i = 0
        while (i < rawBytes.size) {
            val b = rawBytes[i]
            if (b == '\\'.code.toByte() && i + 1 < rawBytes.size) {
                val next = rawBytes[i + 1].toInt().toChar()
                when (next) {
                    'n' -> { unescaped.write('\n'.code); i += 2 }
                    'r' -> { unescaped.write('\r'.code); i += 2 }
                    't' -> { unescaped.write('\t'.code); i += 2 }
                    'b' -> { unescaped.write('\b'.code); i += 2 }
                    'f' -> { unescaped.write(12); i += 2 }
                    '(' -> { unescaped.write('('.code); i += 2 }
                    ')' -> { unescaped.write(')'.code); i += 2 }
                    '\\' -> { unescaped.write('\\'.code); i += 2 }
                    in '0'..'7' -> {
                        // Octal escape \ddd
                        var octalVal = next - '0'
                        var octalLen = 1
                        while (octalLen < 3 && i + 1 + octalLen < rawBytes.size && rawBytes[i + 1 + octalLen].toInt().toChar() in '0'..'7') {
                            octalVal = octalVal * 8 + (rawBytes[i + 1 + octalLen].toInt().toChar() - '0')
                            octalLen++
                        }
                        unescaped.write(octalVal)
                        i += 1 + octalLen
                    }
                    '\r', '\n' -> {
                        // Line continuation, ignore
                        i += 2
                        if (next == '\r' && i < rawBytes.size && rawBytes[i].toInt().toChar() == '\n') i++
                    }
                    else -> {
                        unescaped.write(next.code)
                        i += 2
                    }
                }
            } else {
                unescaped.write(b.toInt())
                i++
            }
        }

        val bytes = unescaped.toByteArray()
        if (bytes.isEmpty()) return ""

        // Check for UTF-16BE BOM
        if (bytes.size >= 2 && bytes[0] == 0xFE.toByte() && bytes[1] == 0xFF.toByte()) {
            return String(bytes.copyOfRange(2, bytes.size), Charsets.UTF_16BE)
        }

        // Check if characters should be looked up in cMap
        if (cMap.isNotEmpty()) {
            val mappedSb = StringBuilder()
            var usedCmap = false

            // Check if 2-byte font encoding (e.g. Identity-H / CIDFont)
            if (bytes.size >= 2 && bytes.size % 2 == 0) {
                var matchCount = 0
                for (k in 0 until bytes.size step 2) {
                    val code16 = ((bytes[k].toInt() and 0xFF) shl 8) or (bytes[k + 1].toInt() and 0xFF)
                    if (cMap.containsKey(code16)) {
                        matchCount++
                    }
                }
                if (matchCount > 0 && matchCount >= (bytes.size / 2) / 3) {
                    for (k in 0 until bytes.size step 2) {
                        val code16 = ((bytes[k].toInt() and 0xFF) shl 8) or (bytes[k + 1].toInt() and 0xFF)
                        val mapped = cMap[code16]
                        if (mapped != null) {
                            mappedSb.append(mapped)
                            usedCmap = true
                        } else if (code16 != 0) {
                            mappedSb.append(code16.toChar())
                        }
                    }
                    if (usedCmap) return mappedSb.toString()
                }
            }

            // Single-byte font lookup fallback
            mappedSb.setLength(0)
            for (byteVal in bytes) {
                val unsignedCode = byteVal.toInt() and 0xFF
                val mapped = cMap[unsignedCode]
                if (mapped != null) {
                    mappedSb.append(mapped)
                    usedCmap = true
                } else {
                    mappedSb.append(unsignedCode.toChar())
                }
            }
            if (usedCmap) return mappedSb.toString()
        }

        // Try UTF-8 first, fallback to Windows-1250 (standard for Czech bank PDFs)
        val utf8 = String(bytes, Charsets.UTF_8)
        return if (!utf8.contains('\uFFFD')) {
            utf8
        } else {
            String(bytes, cp1250Charset)
        }
    }

    private fun decodeHexText(hex: String, cMap: Map<Int, String>): String {
        if (hex.isBlank()) return ""
        val paddedHex = if (hex.length % 2 != 0) "${hex}0" else hex

        // 1. Try CMap lookup with 4-hex digit codes (2 bytes) or 2-hex digit codes
        if (cMap.isNotEmpty()) {
            val sb = StringBuilder()
            if (paddedHex.length % 4 == 0) {
                var k = 0
                while (k + 4 <= paddedHex.length) {
                    val code = paddedHex.substring(k, k + 4).toIntOrNull(16) ?: 0
                    sb.append(cMap[code] ?: hexToUnicodeString(paddedHex.substring(k, k + 4)))
                    k += 4
                }
                return sb.toString()
            } else if (paddedHex.length % 2 == 0) {
                var k = 0
                while (k + 2 <= paddedHex.length) {
                    val code = paddedHex.substring(k, k + 2).toIntOrNull(16) ?: 0
                    sb.append(cMap[code] ?: hexToUnicodeString(paddedHex.substring(k, k + 2)))
                    k += 2
                }
                return sb.toString()
            }
        }

        // 2. Try UTF-16BE if begins with FEFF or alternate bytes are zero
        if (paddedHex.startsWith("FEFF", ignoreCase = true) || (paddedHex.length >= 4 && paddedHex.startsWith("00"))) {
            val bytes = ByteArray(paddedHex.length / 2)
            for (idx in bytes.indices) {
                bytes[idx] = paddedHex.substring(idx * 2, idx * 2 + 2).toInt(16).toByte()
            }
            return if (bytes.size >= 2 && bytes[0] == 0xFE.toByte() && bytes[1] == 0xFF.toByte()) {
                String(bytes.copyOfRange(2, bytes.size), Charsets.UTF_16BE)
            } else {
                String(bytes, Charsets.UTF_16BE)
            }
        }

        // 3. Single-byte hex decoded with Windows-1250 / ISO-8859-1
        val bytes = ByteArray(paddedHex.length / 2)
        for (idx in bytes.indices) {
            bytes[idx] = paddedHex.substring(idx * 2, idx * 2 + 2).toInt(16).toByte()
        }
        val utf8 = String(bytes, Charsets.UTF_8)
        return if (!utf8.contains('\uFFFD')) utf8 else String(bytes, cp1250Charset)
    }


    private fun extractFallbackText(rawText: String): List<String> {
        val lines = mutableListOf<String>()
        val dateRegex = Regex("""\b\d{1,2}\.\s*\d{1,2}\.\s*\d{4}\b""")
        val rawLines = rawText.lines().map { it.trim() }.filter { it.isNotBlank() }
        for (line in rawLines) {
            if (dateRegex.containsMatchIn(line) || line.contains("CZK", ignoreCase = true) || line.contains("Kč")) {
                lines.add(line)
            }
        }
        return lines
    }
}
